---
title: "chip differential broad without E4"
output: html_notebook
---



```{r}
suppressPackageStartupMessages({
  library(DESeq2)
  library(ggplot2)
  library(pheatmap)
  library(RColorBrewer)
  library(gplots)
  library(ggplot2)
  library(KEGG.db)
  library(GO.db)
  library(goseq)
  library(TxDb.Hsapiens.UCSC.hg19.knownGene)
  library(org.Hs.eg.db)
  library(GenomeInfoDb)
  library(ChIPseeker)
  library(rGREAT)
  source("chip_functions.R")
})
```



# create directories
```{r}
mainDir=getwd()
subDir="plots"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
subDir="plots/MDS_PCA_Heatmap"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
subDir="fdr0.05"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
subDir="fdr0.05/fold2"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
subDir="fdr0.1"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
subDir="fdr0.1/fold2"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
subDir="otheroutput"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
subDir="countdata"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
subDir="annotation"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
subDir="ontology"
dir.create(file.path(mainDir,subDir), showWarnings = FALSE)
```

# Read counts table
```{r}
path="count-tables/"
df = read.table(paste0(path,"merged_H3K27me3_counts.tsv"),sep="\t",header=T,row.names = 1)
#head(df[,1:3])
paste0(nrow(df),"*",ncol(df))
dim(df)
outputname = "H3K27me3"
df = df[,grepl(outputname,colnames(df)),]
df = df[!grepl("input",colnames(df))]
dim(df)
```

# deign.matrix
```{r}
#design.matrix = data.frame(treatment=c("3dayNorm","3dayNorm","8wkNorm","8wkNorm","8wkHyp","8wkHyp"))
#row.names(design.matrix) = colnames(df)
design.matrix = read.table(paste0(path,"design.tsv"),sep="\t",col.names=c("file","treatment","histone","batch"),
                           stringsAsFactors = F)
row.names(design.matrix) = design.matrix$file
design.matrix$file = NULL
design.matrix
```


```{r}
df1 = df[,colnames(df) %in% row.names(design.matrix),]
exclude = c("H8_H3K9me2_E2",
            "N3_H3K9me2_E2",
            "N3_H3K9me2_E6",
            "N3_H3K9me2_E1",
            "N8_H3K9me2_E2",
            "H8_H3K27me3_E4",
            "N8_H3K27me3_E4",
            "N8_H3K4me3_E4",
            "H8_H3K4me3_E4")
df1 = df1[,!colnames(df1) %in% exclude,]
design.matrix1 = design.matrix[colnames(df1),]
#dim(df1)
df1 = df1[,row.names(design.matrix1)]
dim(df1)
dim(design.matrix1)
```

```{r}
head(df1[,1:5])
```

```{r}
colnames(df1)
```

```{r}
summary(colnames(df1) == row.names(design.matrix1))
```


```{r}
design.matrix1 = design.matrix1[colnames(df1),]
design.matrix1$treatment = factor(design.matrix1$treatment)
design.matrix1$histone = factor(design.matrix1$histone)
design.matrix1$batch = factor(design.matrix1$batch)
design.matrix1
```

```{r}
levels(design.matrix1$histone)
```


#write design matrix
```{r}
outputname = paste0(outputname,"_withoutE4")
write.table(design.matrix1,file = paste0("design_matrix_hyp-norm_",outputname,".tsv"),sep = "\t", quote = F, col.names = NA)
```

# Granges for all regions
```{r}
#path="/home/master/WORK/atac/private/remi/aug14.2016_alldata/DESEQ2/bedfiles/"
bedfile="count-tables/H3K27me3_merged.bed"
totalwindows=create_granges_frombed3(paste0(bedfile))
length(totalwindows)
cutoff = 100
df_new <- df1[ rowSums(df1) > cutoff,  ]
paste0(nrow(df_new),"*",ncol(df_new))
totalwindows_new = create_grangesnew_frombed3(data.frame(totalwindows)[as.logical(rowSums(df1) >cutoff),])
nrow(df_new)
length(totalwindows_new)
```

```{r}
dim(df_new)
```

# DESEQ2 call parent vs non parent
```{r}
dds  = DESeqDataSetFromMatrix(countData= df_new, colData= design.matrix1, ~ treatment  + batch , rowRanges=totalwindows_new)
dds =  DESeq(dds)#, minReplicatesForReplace=Inf)
# dds <- estimateSizeFactors(dds)
# dds <- estimateDispersions(dds)
# dds <- nbinomWaldTest(dds, maxit=500)
rld <-varianceStabilizingTransformation(dds,blind = TRUE)
ret <- counts(dds, normalized=T) 
write.table(ret,file = paste0("countdata/chip_countdata",outputname,"_DESEQ2_norm.tsv"),sep="\t",row.names = TRUE,quote = FALSE,col.names = NA)
write.table(assay(rld),file = paste0("countdata/chip_countdata",outputname,"_RLD.tsv"),sep="\t",row.names = TRUE,quote = FALSE,col.names = NA)
save(dds,file=paste0(outputname,"_dds.Robj"))
save(rld,file=paste0(outputname,"_rld.Robj"))
```

```{r}
rld3 = rld
assay(rld3) <- limma::removeBatchEffect(assay(rld3), rld3$batch)

rld1 =rld3
  showcols <- brewer.pal(8, "Set1")[1:length(unique(colData(rld1)$treatment))]
  a=data.frame(name=colData(rld1)$treatment)
  data <- plotPCA(rld1, intgroup="treatment", ntop = 1000,returnData=TRUE)
  percentVar <- round(100 * attr(data, "percentVar"))
  #pdf(file =  paste0("plots/",output.name,"_RNA_PCA.pdf"))
  ggplot(data, aes(PC1, PC2,label=rownames(data)))+ theme_bw() +
    theme(axis.line = element_line(colour = "black"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          #panel.border = element_blank(),
          panel.background = element_blank()) +
   geom_text(col=showcols[factor(a$name)],size=1.5,check_overlap = FALSE)+
    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
    ylab(paste0("PC2: ",percentVar[2],"% variance"))
ggsave(filename =paste0("plots/MDS_PCA_Heatmap/",outputname,"_chip_PCA.pdf") )

  rlogcount <- assay(rld1)
  sampleDists <- as.matrix(dist(t(rlogcount)))
  sampleDists
  showcols <- brewer.pal(8, "Set1")[1:length(unique(colData(rld1)$treatment))]
  a=data.frame(name=colData(rld1)$treatment)
  hmcol <- colorRampPalette(brewer.pal(9, "GnBu"))(100)
  pdf(file = paste0("plots/MDS_PCA_Heatmap/",outputname,"_sampledist.pdf"))
  heatmap.2(as.matrix(sampleDists), key=F, trace="none",
            col=hmcol,
                ColSideColors=showcols[factor(a$name)], 
                RowSideColors=showcols[factor(a$name)],
            margin=c(10, 10))
  dev.off()
```

```{r}
write.table(sampleDists,file = paste0("sampledist_",outputname,".tsv"),sep="\t",quote = F,col.names = NA)
```

```{r}
resultsNames(dds)
```



# 1.8wkNorm_vs_8wkHyp
```{r}
outputname = "Comparison1.1_h3k27me3_8wkNorm_vs_8wkHyp_withoutE4"
res = results(dds, alpha=0.05, contrast = c("treatment","8wkNorm","8wkHyp"),format = "GRanges")
keep1 = rowSums(counts(dds[,dds$treatment %in% c("8wkNorm")]) >= 5) >= 1
keep2 = rowSums(counts(dds[,dds$treatment %in% c("8wkHyp")]) >= 5) >= 1
res.sub = res[keep1 & keep2,]
summary(res.sub)
rld.sub = rld
print(outputname)
colData(rld.sub)
createoutput(res.sub,rld.sub, outputname)
```

